# Generated by Django 4.1.4 on 2022-12-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0016_auto_20220301_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=str, max_length=300, verbose_name='프로젝트 제목')),
                ('date', models.CharField(default=str, max_length=300, verbose_name='날짜')),
                ('images', models.ImageField(upload_to='news')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_end_date',
            field=models.DateField(verbose_name='프로젝트 종료일'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_strat_date',
            field=models.DateField(verbose_name='프로젝트 시작일'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='support_department',
            field=models.CharField(blank=True, default=str, max_length=40, verbose_name='주관부서'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(default=str, max_length=300, verbose_name='프로젝트 제목'),
        ),
    ]
