# Generated by Django 4.1.4 on 2022-12-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0017_news_alter_projects_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='year',
            field=models.IntegerField(default=int, verbose_name='년'),
        ),
    ]
