# Generated by Django 3.2.16 on 2022-12-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0019_auto_20221214_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
    ]
