# Generated by Django 3.2.16 on 2022-12-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0020_remove_news_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
    ]
