# Generated by Django 4.1.4 on 2023-01-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cailab', '0021_alter_news_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['project_strat_date']},
        ),
        migrations.AddField(
            model_name='biography',
            name='is_bc',
            field=models.BooleanField(default=False),
        ),
    ]
